[
    {
        "test_file": "perform_search",
        "test": "test",
        "set_name": "",
        "environment": "",
        "result": "code error",
        "description": "Perform a search for an article. verity that the title is correct",
        "browser": "edge",
        "test_data": {},
        "steps": [
            {
                "message": "Navigate to: 'https://wikipedia.org'",
                "screenshot": null,
                "error": null
            },
            {
                "message": "Error",
                "screenshot": null,
                "error": {
                    "message": "Exception: No executable file found using path ./drivers/edgedriver*",
                    "description": "Traceback (most recent call last):\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\test_runner\\test_runner.py\", line 257, in run_test_function\n    f(execution.data)\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\tutorial\\projects\\Akshy\\tests\\perform_search.py\", line 7, in test\n    navigate(\"https://wikipedia.org\")\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\actions.py\", line 1379, in navigate\n    get_browser().get(url)\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\actions.py\", line 1097, in get_browser\n    return browser.get_browser()\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\browser.py\", line 235, in get_browser\n    open_browser()\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\browser.py\", line 158, in open_browser\n    with validate_exec_path('edge', 'edgedriver_path', settings) as ex_path:\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\contextlib.py\", line 119, in __enter__\n    return next(self.gen)\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\browser.py\", line 88, in validate_exec_path\n    raise Exception(msg)\nException: No executable file found using path ./drivers/edgedriver*"
                }
            }
        ],
        "errors": [
            {
                "message": "Exception: No executable file found using path ./drivers/edgedriver*",
                "description": "Traceback (most recent call last):\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\test_runner\\test_runner.py\", line 257, in run_test_function\n    f(execution.data)\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\tutorial\\projects\\Akshy\\tests\\perform_search.py\", line 7, in test\n    navigate(\"https://wikipedia.org\")\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\actions.py\", line 1379, in navigate\n    get_browser().get(url)\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\actions.py\", line 1097, in get_browser\n    return browser.get_browser()\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\browser.py\", line 235, in get_browser\n    open_browser()\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\browser.py\", line 158, in open_browser\n    with validate_exec_path('edge', 'edgedriver_path', settings) as ex_path:\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\contextlib.py\", line 119, in __enter__\n    return next(self.gen)\n  File \"C:\\Users\\devad\\PycharmProjects\\golem\\venv\\lib\\site-packages\\golem\\browser.py\", line 88, in validate_exec_path\n    raise Exception(msg)\nException: No executable file found using path ./drivers/edgedriver*"
            }
        ],
        "elapsed_time": 0.02,
        "timestamp": "2024.04.28.14.17.26.945"
    }
]